site_name: "Replicat Charts"
site_description: "Repeatable charts for Django"
site_author: "jacklinke"
site_url: "https://jacklinke.com/"

# Copyright
copyright: "&copy; 2021 Jack Linke"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/jacklinke/replicat-charts"
edit_uri: "https://github.com/jacklinke/replicat-charts/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "pink"
    accent: "pink"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #logo: 'assets/images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  # manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/jacklinke"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/JackDLinke"

# Page tree
nav:
  - "Home": "index.md"
  # - "Getting started":
  #     - "Download boilerplate": "getting-started/download-boilerplate.md"
  #     - "pipenv": "getting-started/pipenv.md"
  #     - "invoke": "getting-started/invoke.md"
  #     - "Docker": "getting-started/docker.md"
  #     - "pip": "getting-started/pip.md"
  # - "Hosting and Deployment":
  #     - "Combinations": "hosting-and-deployment/combinations.md"
  #     - "Netlify": "hosting-and-deployment/netlify.md"
  #     - "GitHub Pages": "hosting-and-deployment/github-pages.md"
  #     - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
  #     - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  # - "Extensions":
  #     - "MathJax": "extensions/mathjax.md"
  #     - "Code Hilite": "extensions/code-hilite.md"
  #     - "Footnote": "extensions/footnote.md"
  - "License": "license.md"
