# Generated by Django 3.2.5 on 2021-07-21 06:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import replicat_documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentIssuerChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "issuer_path",
                    models.TextField(
                        editable=False,
                        help_text="Full dot-notation path to the issuer class. e.g.: 'account.issuers.documents.issuer_name.IssuerName'",
                        unique=True,
                        verbose_name="Issuer Path",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        editable=False,
                        help_text="The descriptive label for this Document Issuer",
                        max_length=100,
                        unique=True,
                        verbose_name="Label",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplicatDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID for the Document as an UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        help_text="Generated document identifier", null=True, unique=True, verbose_name="Document ID"
                    ),
                ),
                (
                    "context",
                    replicat_documents.models.PydanticModelField(
                        blank=True,
                        editable=False,
                        help_text="Context used to render the document's template",
                        null=True,
                        verbose_name="Collected context",
                    ),
                ),
                (
                    "context_query",
                    replicat_documents.models.PydanticModelField(
                        help_text="Context will be fetched from those parameters",
                        verbose_name="Context query parameters",
                    ),
                ),
                ("rendered_to_pdf_at", models.DateTimeField(null=True, verbose_name="Rendered to PDF at")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time at which the document was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time at which the document was last updated",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        help_text="The issuer of the document among allowed ones",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="replicat_documents.documentissuerchoice",
                        verbose_name="Issuer",
                    ),
                ),
            ],
        ),
    ]
